### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/james-branch-cabell_chivalry#1]
# General Issues:

- [x] Sentence case the beginning clause of the bridgeheads ([SEMOS 7.2.11.4](https://standardebooks.org/manual/1.7.4/single-page#7.2.11.4)).

# prologue.xhtml:

- [x] `A Sa Dame` should be in the `<header>` element. It looks like a dedication.

# chapter-6.xhtml:

- [x] The verse that begins "Mater, ora filium..." should be in a `<blockquote>` element because it's quoted hymn lyrics. The indentation will need to be adjusted. It's very rare to have a `<blockquote>` inside of a `<blockquote>`.

# epilogue.xhml:

- [x] `A Son Livret` should be in the `<header>` element. It looks like a dedication.

- [x] Apply the language tag to the `<b>` element around `Explicit Decas Reginarum`.

# local.css:

- [x] The custom CSS in chapter 7 can be simplified as:
```
/* editorial div */
#chapter-7 div{
	font-style: italic;
	margin: 1em 0 1em 0;
}

#chapter-7 div > p{
	text-indent: 1em;
}
/* end editorial div */
```

- [x] Replace the subchapter heading CSS with the SEMOS header CSS ([7.2.10.8](https://standardebooks.org/manual/1.7.4/single-page#7.2.10.8)).

**Comment by javamanatee** [comment]
I think I got everything, and it's ready for another look. For SEMOS header CSS, it was making all of the headers have small caps, including the epigraphs and bridgeheads. So I tried to make that rule more selective again -- not sure how else to make it work.

**Comment by EmmaSweeney** [comment]
The header CSS looks good. Just a few more tweaks:

- [x] In the prologue and epilogue, add `epub:type="dedication"` to "A Sa Dame" and "A Son Livret".

- [x] The styling for these dedication lines can be simplified as:
```
header [epub|type~="dedication"]{
	margin-top: 1em;
}
```

**Comment by javamanatee** [comment]
Should the epub:type="dedication" go on the <p> tags for "A Sa Dame" and "A Son Livret"?  If I do that, then the header/dedication CSS does not have a target (lint complains.)

**Comment by EmmaSweeney** [comment]
It should look like:
```
				<p epub:type="dedication">
					<i xml:lang="fr">A Sa Dame</i>
				</p>
```

Lint isn't showing me an error when I test it with your repo. If you keep getting an error, push the changes to your repo and I'll take another look.

**Comment by javamanatee** [comment]
I see it now. I missed a space in the CSS selector, that makes a difference!  It's clean now, back over to you.
